//import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

//const geistSans = Geist({
 // variable: "--font-geist-sans",
  //subsets: ["latin"],});

//const geistMono = Geist_Mono({
  //variable: "--font-geist-mono",
  //subsets: ["latin"],});

//export const metadata = {
 // title: "Create Next App",
  //description: "Generated by create next app",};

  export const metadata = {
    title: "Clínica",
    description: "clínica hopitalar",
    charset:'UTF-8',
    author:'Marianny Gonçalves',
    keywords:'HTML, CSS, ',
  };

//export default function RootLayout({ children }) {
  //return (
   // <html lang="en">
     // <body className={`${geistSans.variable} ${geistMono.variable}`}>
     //   {children}
    //  </body>
   // </html> );}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header/>
        {children}
      </body>
    </html>
  );
}
